<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="2" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.45" />
  <xacro:property name="base_length" value="0.5" />
  <xacro:property name="base_height" value="0.03" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.025" />
  <xacro:property name="wheel_radius" value="0.08" />
  <xacro:property name="z_offset" value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint -->



  <link name = "base_link">
        <visual>
            <geometry>
                <box size = "0.5 0.45 0.03" />
            </geometry>
            <origin xyz = "0 0 0.095" rpy = "0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size = "0.5 0.45 0.03" />
            </geometry>
            <origin xyz = "0 0 0.095" rpy = "0 0 0" />
        </collision>
        <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>

    <link name = "base_arm_link">
        <visual>
            <geometry>
                <cylinder radius="0.125" length="0.10" />
            </geometry>
            <origin xyz = "0 0 0.05" rpy = "0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.125" length="0.10" />
            </geometry>
            <origin xyz = "0 0 0.05" rpy = "0 0 0" />
        </collision>
    </link>

    <link name = "shoulder_z_link">
        <visual>
            <geometry>
                <cylinder radius="0.075" length="0.1" />
            </geometry>
            <origin xyz = "0 0 0.05" rpy = "0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.075" length="0.10" />
            </geometry>
            <origin xyz = "0 0 0.05" rpy = "0 0 0" />
        </collision>
    </link>

    <link name = "shoulder_x_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.28" />
            </geometry>
            <origin xyz = "0 0 -0.14" rpy = "0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.28" />
            </geometry>
            <origin xyz = "0 0 -0.14" rpy = "0 0 0" />
        </collision>
    </link>

    <link name = "elbow_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.12" />
            </geometry>
            <origin xyz = "0 0 0.06" rpy = "0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.12" />
            </geometry>
            <origin xyz = "0 0 0.06" rpy = "0 0 0" />
        </collision>
    </link>

    <link name = "wrist_link">
        <visual>
            <geometry>
                <cylinder radius="0.04" length="0.12" />
            </geometry>
            <origin xyz = "0 0 -0.06" rpy = "0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.04" length="0.12" />
            </geometry>
            <origin xyz = "0 0 0.06" rpy = "0 0 0" />
        </collision>
    </link>

    <link name = "gripper_link">
        <visual>
            <geometry>
                <cylinder radius="0.03" length="0.24" />
            </geometry>
            <origin xyz = "0 0 0.12" rpy = "0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.03" length="0.24" />
            </geometry>
            <origin xyz = "0 0 0.1" rpy = "0 0 0" />
        </collision>
    </link>

    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.025" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size = "0.1 0.1 0.025" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
        </collision>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="0.08" length="0.025" />
                </geometry>
            <origin xyz ="0 0 0" rpy ="-1.57 0 0" />
            <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.08" length="0.025" />
                </geometry>
            <origin xyz ="0 0 0" rpy = "1.57 0 0" />
            </collision>
            <inertia
                ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
                iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
                izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="front_left" />
    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="back_left" />
    <xacro:wheel_link prefix="back_right" />

    <joint name="base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_arm_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" /> 
    </joint>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar" />
        <origin xyz="0.18 0 0.1075" rpy="0 0 0" /> 
    </joint>

    <joint name="base_shoulder_z_joint" type="revolute">
        <parent link="base_arm_link" />
        <child link="shoulder_z_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="1.57" upper="4.71" velocity="100" effort="100" />
    </joint>

    <joint name="base_shoulder_x_joint" type="revolute">
        <parent link="shoulder_z_link" />
        <child link="shoulder_x_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="1.57" upper="4.71" velocity="100" effort="100" />
    </joint>

    <joint name="shoulder_x_elbow_joint" type="revolute">
        <parent link="shoulder_x_link" />
        <child link="elbow_link" />
        <origin xyz="0 0 -0.28" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="1.57" upper="4.71" velocity="100" effort="100" />
    </joint>

    <joint name="elbow_wrist_joint" type="revolute">
        <parent link="elbow_link" />
        <child link="wrist_link" />
        <origin xyz="0 0 0.12" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="1.57" upper="4.71" velocity="100" effort="100" />
    </joint>

    <joint name="wrist_gripper_joint" type="revolute">
        <parent link="wrist_link" />
        <child link="gripper_link" />
        <origin xyz="0 0 -0.12" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="1.57" upper="4.71" velocity="100" effort="100" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel"/>
        <origin xyz="-0.15 0.2375 0.04" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <origin xyz="-0.15 -0.2375 0.04" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel"/>
        <origin xyz="0.15 0.2375 0.04" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel" />
        <origin xyz="0.15 -0.2375 0.04" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>


  <!-- Base Link
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${base_width/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint> -->

    <!-- left wheel Link -->
    <!-- <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0 ${base_width/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint> -->

    <!-- right wheel Link -->
    <!-- <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>

    <joint name="${prefix}caster_frontal_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}caster_frontal_wheel"/>
      <origin xyz="${base_width/2 - caster_wheel_radius} 0 ${z_offset}" rpy="0 0 0"/>
    </joint> -->

    <!-- caster frontal wheel Link -->
    <!-- <link name="${prefix}caster_frontal_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link>

    <joint name="${prefix}caster_rear_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}caster_rear_wheel"/>
      <origin xyz="${-base_width/2 + caster_wheel_radius} 0 ${z_offset}" rpy="0 0 0"/>
    </joint> -->

    <!-- caster rear wheel Link -->
    <!-- <link name="${prefix}caster_rear_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link> -->

  </xacro:macro>

</robot>
